export const servicesData = [
  {
    id: "merchandising",
    title: "Merchandising",
    titleEn: "Merchandising",
    shortDescription: "Planning and executing strategies to maximize product sales",
    description: "Our field marketing specialists plan and execute strategies aimed at maximizing product sales through managing product distribution, inventory, and visual displays in stores or online environments. We ensure products are available in sufficient quantities and placed in strategic locations to ensure visibility by customers and effectively promoted to attract shoppers and increase revenue. Our specialists also conduct market research to understand trends and consumer preferences, helping make informed decisions about product selection and pricing.",
    features: ["Distribution Management", "Visual Displays", "Inventory Management", "Market Research"],
  },
  {
    id: "field-promotion",
    title: "Field Promotion",
    titleEn: "Field Promotion",
    shortDescription: "Direct brand representation and customer engagement",
    description: "Field promoters serve as direct representatives of the brand, employed to create interest in a product or service. They interact directly with customers, often in-store at events or in public places. Unlike traditional sales staff, promoters are often employed by the product manufacturer. Key tasks include conducting demonstrations, increasing brand awareness, direct interaction, event presence, and collecting customer feedback.",
    features: ["Product Demonstrations", "Brand Awareness", "Direct Interaction", "Feedback Collection"],
  },
  {
    id: "product-sampling",
    title: "Product Sampling",
    titleEn: "Product Sampling",
    shortDescription: "Offering free samples to increase awareness and drive sales",
    description: "Product sampling is a marketing strategy where a company provides free samples of its products to potential customers. This method allows consumers to experience the product without any financial risk, helping to increase brand awareness, collect valuable feedback, and drive sales. Common objectives include increasing awareness, encouraging purchases, gathering feedback, building customer loyalty, and creating positive buzz through word of mouth.",
    features: ["Free Samples", "Brand Awareness", "Feedback Collection", "Sales Activation"],
  },
  {
    id: "distribution",
    title: "Distribution",
    titleEn: "Distribution",
    shortDescription: "Delivering products to consumers efficiently and professionally",
    description: "Distribution is the comprehensive process aimed at delivering a product or service to consumers or business users. This process includes all stages the product goes through from the factory to the final point of purchase, including logistics, transportation, and inventory management. As a key element of the marketing mix, developing an effective distribution strategy is essential for achieving sales and overall company growth.",
    features: ["Logistics", "Transportation", "Inventory Management", "Point of Sale"],
  },
  {
    id: "brand-activation",
    title: "Brand Activation",
    titleEn: "Brand Activation",
    shortDescription: "Creating interactive and immersive experiences that connect brands with audiences",
    description: "Brand activation is a strategic marketing process aimed at creating interactive and immersive experiences that directly connect the brand with its target audience. Unlike traditional passive advertising, brand activation seeks to bring the brand to life by engaging consumers emotionally and motivating them to take action, thereby enhancing long-term loyalty. Benefits include increased awareness, enhanced engagement, emotional connection building, valuable insights, and differentiation from competitors.",
    features: ["Interactive Experiences", "Emotional Engagement", "Loyalty Building", "Consumer Insights"],
  },
  {
    id: "mystery-shopper",
    title: "Mystery Shopper",
    titleEn: "Mystery Shopper",
    shortDescription: "Evaluating service quality through customer experience assessment",
    description: "Mystery shoppers perform a set of procedures according to detailed criteria provided by the commissioning company. This process is used in a wide range of sectors such as retail stores, restaurants, banks, and hotels to assess service quality and customer experience. Tasks include evaluating employee performance, measuring service time, observing cleanliness, documenting promotional materials, and executing specific scenarios. Benefits include real data, service improvement, identifying training needs, and ensuring compliance with standards.",
    features: ["Performance Evaluation", "Real Data", "Service Improvement", "Standards Assurance"],
  },
  {
    id: "reporting-system",
    title: "Reporting System",
    titleEn: "Reporting System",
    shortDescription: "Collecting data and transforming it into actionable information",
    description: "A reporting system is a tool or process used to collect data, organize it into reports, and distribute it to stakeholders to support decision-making. In a business context, this system transforms raw data from multiple sources into useful and actionable information. An effective reporting system contributes to providing clear insights into past performance, tracking key indicators, and guiding future strategies. Benefits include enabling better decisions, increasing efficiency, enhancing overall visibility, facilitating communication, and ensuring accountability.",
    features: ["Data Extraction", "Information Analysis", "Automated Reports", "Performance Indicators"],
  },
  {
    id: "research-surveys",
    title: "Research & Surveys",
    titleEn: "Research & Surveys",
    shortDescription: "Collecting and analyzing data to understand the market and consumers",
    description: "Research is a systematic process aimed at collecting, analyzing, and interpreting information to understand the market, product, service, or consumer behavior. It forms the foundation for making informed business decisions and developing effective strategies. Surveys as a market research tool are commonly used to collect data directly from a sample of people. Benefits include cost efficiency, enhanced data-driven decisions, direct feedback, and flexibility in use.",
    features: ["Market Analysis", "Surveys", "Consumer Insights", "Informed Decisions"],
  },
  {
    id: "video-production",
    title: "Video Production",
    titleEn: "Video Production",
    shortDescription: "Designing, filming, and editing professional promotional videos",
    description: "Video production is the process of designing, filming, and editing videos to promote a product or service in an attractive and quick manner, often displayed on social media platforms like TikTok, Instagram, and YouTube. It includes phases: pre-production (preparation and planning), production (filming and sound recording), and post-production (editing and effects). Creative concept, script, filming location, and actors are selected, then the video is cut and edited with effects and music added.",
    features: ["Professional Filming", "Expert Editing", "Visual Effects", "Creative Script"],
  },
  {
    id: "branding",
    title: "Branding",
    titleEn: "Branding",
    shortDescription: "Creating and crafting a unique identity for companies or products",
    description: "Branding is a strategic process aimed at creating and crafting a unique identity for a company, product, or service to distinguish it from competitors in consumers' minds. Branding is not limited to just a logo or name but includes the mental image, reputation, and emotional connection the customer builds with the business. Benefits of strong branding include increased recognition and differentiation, building trust and loyalty, competitive advantage, ease of expansion, and increased market value.",
    features: ["Identity Design", "Brand Guidelines", "Visual Identity", "Strategic Positioning"],
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    titleEn: "Digital Marketing",
    shortDescription: "Using digital channels to promote and communicate with customers",
    description: "Digital marketing is the use of digital channels, platforms, and technologies to promote products and services, build brand awareness, and communicate with customers. This includes all marketing efforts that rely on the internet or electronic devices such as websites, social media, email, and smartphone applications. Digital marketing has become an essential part of modern business strategies. Benefits include global reach, cost reduction, measurable results, precise targeting, enhanced engagement, and personalization.",
    features: ["Social Media", "SEO", "Email Marketing", "Analytics"],
  },
  {
    id: "creative-campaigns",
    title: "Creative Campaigns",
    titleEn: "Creative Campaigns",
    shortDescription: "Innovative marketing campaigns based on impactful storytelling",
    description: "Creative campaigns are short-term marketing initiatives based on innovative concepts, designs, and impactful storytelling to capture the target audience's attention and achieve a specific business goal. These campaigns are not limited to direct product promotion but seek emotional connection with consumers to build brand awareness, enhance engagement, and increase sales. Key components include a strong central idea, memorable storytelling, integrated approach, unique and shareable content, and measurable results.",
    features: ["Creative Concept", "Storytelling", "Integrated Approach", "Unique Content"],
  },
  {
    id: "media-production",
    title: "Media Production",
    titleEn: "Media Production",
    shortDescription: "Creating and distributing content across multiple media channels",
    description: "Media production is the complete process of creating and distributing content across multiple media channels including video, audio, and digital formats. This includes the creative and technical work needed to transform an idea into a final product ready for publication and public consumption. Types of media production include video production, audio production (podcasts and radio programs), digital media production, and print media production.",
    features: ["Video Production", "Audio Production", "Digital Media", "Print Media"],
  },
  {
    id: "photography",
    title: "Photography",
    titleEn: "Photography",
    shortDescription: "Capturing professional images to express products and services",
    description: "Photography is the art, science, and practice of creating images by recording light either electronically using a digital sensor or chemically using light-sensitive film. Photography is a versatile medium used in artistic expression, scientific documentation, marketing and advertising, and photojournalism. Professionals use advanced techniques to capture distinctive moments and transform them into powerful images that serve commercial and creative purposes.",
    features: ["Professional Photos", "Advanced Editing", "Professional Lighting", "Creative Composition"],
  },
  {
    id: "video-shooting",
    title: "Video Shooting",
    titleEn: "Video Shooting",
    shortDescription: "Recording moving images and sound using digital media",
    description: "Videography is the art and process of recording moving images and sound using digital media such as video cameras and DSLR cameras. The videographer is responsible for this work and often manages all production stages from filming to editing. Types of videography projects include event filming, weddings, corporate content, documentary filming, promotional videos, tutorials and reviews, aerial filming, and live streaming.",
    features: ["Professional Filming", "Advanced Lighting", "Clear Audio", "Expert Editing"],
  },
  {
    id: "technical-services",
    title: "Technical Services Activation",
    titleEn: "Technical Services Activation",
    shortDescription: "Enabling and configuring technical services for clients effectively",
    description: "Technical services activation is the comprehensive process of enabling and configuring a technical service for a client so they can use it effectively. This concept applies to a wide range of fields, from activating a new mobile phone plan to deploying complex software solutions in an enterprise environment. Process stages include ordering and registration, resource allocation, technical setup, integration, testing and verification, and service operation. Benefits include reducing failures and ensuring a positive customer experience.",
    features: ["Technical Setup", "System Integration", "Comprehensive Testing", "Customer Support"],
  },
];
